### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by karanOnLoop** [NisargPethani/Face-Mask-Detection-using-YOLO-v3#2]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

does your workspace have GPU?

**Comment by karanOnLoop** [comment]
if opt.weights_path.endswith(".weights"):
        model.load_darknet_weights(opt.weights_path)  # Load weights
    else:
        model.load_state_dict(torch.load(opt.weights_path), map_location='cpu')  # Load checkpoints


even I have put map_location = 'cpu' still getting error

**Comment by harshkumar900** [comment]
Hi @Karan7879 may i know how you solved this issue?
